### PR TITLE
Fix #73

### LINKED ISSUE #73: Colorized text doesn't work in localizations
Special tags like `<GreenHighlight>`, `<SolidHighlight>`, etc. are not processed in the localization files. The stock strings are processed via `TextColors.ColorizeText` during the localization load.

### PR DESCRIPTION
**Pull request by ihsoft**

### CODE REVIEW

**Comment by KYPremco** [comment]
Thanks, i'm going to test this when i'm patching the meshy problem!

**Comment by ihsoft** [comment]
> ps. Do you have any examples and screenshots of the problem / solution

Simply add any localization string, like "Test <SolidHighlight>solid</SolidHighlight>" into TimberAPI `lang` folder. Then, try to get this value via `Loc.T`. In the result the solid tag should have replaced with Unity's `<color>` rich text tag, but it won't happen in TimberAPI. On the other hand, if you check the stock localization strings, you may find many examples there. Like:
```
Work.BeaverOnly,<SolidHighlight>Beaver-only:</SolidHighlight> Only beavers are allowed to work in this workplace.,Shown on a tooltip at workplaces where only beavers can work in
```

File: Core/TimberApi/LocalizationSystem/LocalizationFetcher.cs [hunk 1]
```diff
@@ -27,7 +27,7 @@ internal static class LocalizationFetcher
                 string id = defaultRecord.Id;
                 if (!localizedRecords.TryGetValue(id, out string text) || string.IsNullOrEmpty(text))
                 {
-                    localizedRecords[id] = defaultRecord.Text;
+                    localizedRecords[id] = TextColors.ColorizeText(defaultRecord.Text);
```
Comment (KYPremco) [inline Core/TimberApi/LocalizationSystem/LocalizationFetcher.cs:30]: This is fine, but won't fix the issue you having since it's for the fallback.

Change the localizedRecords line to
`            Dictionary<string, string> localizedRecords = GetLocalizationRecordsFromFiles(localizationKey, GetLocalizationFilePathsFromDependencies(localizationKey))
                .ToDictionary(record => record.Id, record => TextColors.ColorizeText(record.Text));`

Then it works for all

**Review by KYPremco — CHANGES_REQUESTED** [review]

File: Core/TimberApi/LocalizationSystem/LocalizationFetcher.cs (hunk 1 above)
Comment (ihsoft) [reply Core/TimberApi/LocalizationSystem/LocalizationFetcher.cs:30]: Done

**Review by KYPremco — APPROVED** [review]
